-- Generated by data.DevelopmentDataGenerator. Do not edit by hand.
-- Foundation-only data: stable IDs and representative reserved/GA records.
SET NAMES utf8mb4;
START TRANSACTION;

INSERT INTO Users
    (user_id, name, address, email, date_of_birth, user_role)
VALUES
    (1001, 'Foundation Organizer', '1 Front Street', 'organizer@foundation.test', '1980-01-15', 'organizer'),
    (2001, 'Alice Foundation', '2 Front Street', 'alice@foundation.test', '1990-02-20', 'customer'),
    (2002, 'Bob Foundation', '3 Front Street', 'bob@foundation.test', '1992-03-25', 'customer');
INSERT INTO Organizer (user_id, user_role) VALUES (1001, 'organizer');
INSERT INTO Customer (user_id, user_role) VALUES
    (2001, 'customer'), (2002, 'customer');
INSERT INTO PaymentInfo
    (payment_info_id, customer_id, card_number, card_holder_name, expiry_date, billing_zip)
VALUES
    (2101, 2001, '4111111111111111', 'Alice Foundation', '2030-12-31', 'M5J 2N8'),
    (2102, 2002, '5555555555554444', 'Bob Foundation', '2031-12-31', 'M5J 2N9');

INSERT INTO Segment (segment_id, segment_name) VALUES (4001, 'Music');
INSERT INTO Genre (genre_id, genre_name, segment_id) VALUES (4101, 'Rock', 4001);
INSERT INTO ArtistsTeams (artist_id, name, type)
VALUES (4201, 'Foundation Band', 'Band');
INSERT INTO Venue
    (venue_id, name, latitude, longitude, address, city, postal_code, country)
VALUES
    (3001, 'Foundation Hall', 43.642600, -79.387100, '100 Front Street West', 'Toronto', 'M5J 1E3', 'Canada');
INSERT INTO Section (venue_id, section_name, section_type, standing_capacity)
VALUES (3001, 'Orchestra', 'reserved', NULL),
       (3001, 'General Floor', 'general', 20);
INSERT INTO SeatRows (venue_id, section_name, section_type, row_name)
VALUES (3001, 'Orchestra', 'reserved', 'A');
INSERT INTO Seats (venue_id, section_name, row_name, seat_number) VALUES
    (3001, 'Orchestra', 'A', 1),
    (3001, 'Orchestra', 'A', 2),
    (3001, 'Orchestra', 'A', 3),
    (3001, 'Orchestra', 'A', 4),
    (3001, 'Orchestra', 'A', 5),
    (3001, 'Orchestra', 'A', 6);

INSERT INTO Event
    (event_id, title, description, resale_cap_pct, organizer_id, genre_id)
VALUES (5001, 'Foundation Concert', 'Deterministic development event', 1.20, 1001, 4101);
INSERT INTO BillingOrder (event_id, artist_id, billing_rank)
VALUES (5001, 4201, 1);
INSERT INTO Performance
    (performance_id, event_id, venue_id, date_time, status)
VALUES
    (6001, 5001, 3001, DATE_ADD(UTC_TIMESTAMP(), INTERVAL 30 DAY), 'scheduled'),
    (6002, 5001, 3001, DATE_ADD(UTC_TIMESTAMP(), INTERVAL 45 DAY), 'scheduled'),
    (6003, 5001, 3001, DATE_SUB(UTC_TIMESTAMP(), INTERVAL 30 DAY), 'completed');

INSERT INTO PriceTier (performance_id, tier_code, price) VALUES
    (6001, 'P1', 100.00), (6001, 'P2', 60.00),
    (6002, 'P1', 110.00), (6002, 'P2', 65.00),
    (6003, 'P1', 90.00), (6003, 'P2', 55.00);
INSERT INTO SectionTierAssignment
    (performance_id, venue_id, section_name, tier_code) VALUES
    (6001, 3001, 'Orchestra', 'P1'),
    (6001, 3001, 'General Floor', 'P2'),
    (6002, 3001, 'Orchestra', 'P1'),
    (6002, 3001, 'General Floor', 'P2'),
    (6003, 3001, 'Orchestra', 'P1'),
    (6003, 3001, 'General Floor', 'P2');
INSERT INTO GeneralAdmissionCapacity
    (ga_capacity_id, performance_id, venue_id, section_name, section_type, total_capacity, remaining_capacity)
VALUES
    (6201, 6001, 3001, 'General Floor', 'general', 20, 20),
    (6202, 6002, 3001, 'General Floor', 'general', 20, 19),
    (6203, 6003, 3001, 'General Floor', 'general', 20, 20);
INSERT INTO PerformanceSeats
    (performance_seat_id, performance_id, venue_id, section_name, row_name, seat_number, blocked_status)
VALUES
    (6101, 6001, 3001, 'Orchestra', 'A', 1, FALSE),
    (6102, 6001, 3001, 'Orchestra', 'A', 2, FALSE),
    (6103, 6001, 3001, 'Orchestra', 'A', 3, FALSE),
    (6104, 6001, 3001, 'Orchestra', 'A', 4, FALSE),
    (6105, 6001, 3001, 'Orchestra', 'A', 5, FALSE),
    (6106, 6001, 3001, 'Orchestra', 'A', 6, TRUE),
    (6111, 6002, 3001, 'Orchestra', 'A', 1, FALSE),
    (6112, 6002, 3001, 'Orchestra', 'A', 2, FALSE),
    (6113, 6002, 3001, 'Orchestra', 'A', 3, FALSE),
    (6114, 6002, 3001, 'Orchestra', 'A', 4, FALSE),
    (6115, 6002, 3001, 'Orchestra', 'A', 5, FALSE),
    (6116, 6002, 3001, 'Orchestra', 'A', 6, FALSE),
    (6121, 6003, 3001, 'Orchestra', 'A', 1, FALSE),
    (6122, 6003, 3001, 'Orchestra', 'A', 2, FALSE),
    (6123, 6003, 3001, 'Orchestra', 'A', 3, FALSE),
    (6124, 6003, 3001, 'Orchestra', 'A', 4, FALSE),
    (6125, 6003, 3001, 'Orchestra', 'A', 5, FALSE),
    (6126, 6003, 3001, 'Orchestra', 'A', 6, FALSE);

INSERT INTO Transactions
    (transaction_id, customer_id, payment_info_id, payment_card_number,
     payment_card_holder_name, payment_expiry_date, payment_billing_zip,
     transaction_type, performance_id, listing_id, transaction_date)
VALUES
    (7001, 2001, 2101, '4111111111111111', 'Alice Foundation', '2030-12-31', 'M5J 2N8', 'purchase', 6001, NULL, DATE_SUB(UTC_TIMESTAMP(), INTERVAL 1 DAY)),
    (7002, 2002, 2102, '5555555555554444', 'Bob Foundation', '2031-12-31', 'M5J 2N9', 'purchase', 6002, NULL, DATE_SUB(UTC_TIMESTAMP(), INTERVAL 1 DAY));
INSERT INTO Tickets
    (ticket_id, purchase_id, performance_id, tier_code, performance_seats_ref,
     general_seats_ref, face_value, status)
VALUES
    (8001, 7001, 6001, 'P1', 6101, NULL, 100.00, 'active'),
    (8002, 7002, 6002, 'P2', NULL, 6202, 65.00, 'active');
INSERT INTO TicketOwnership
    (ownership_id, ticket_id, customer_id, acquired_transaction_id, acquired_listing_id)
VALUES (9001, 8001, 2001, 7001, NULL),
       (9002, 8002, 2002, 7002, NULL);

COMMIT;
