package data;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public final class DevelopmentDataGenerator {
    private static final Path DEFAULT_OUTPUT = Paths.get("data", "development-data.sql");

    private DevelopmentDataGenerator() {
    }

    public static void main(String[] args) throws IOException {
        Path output = args.length == 0 ? DEFAULT_OUTPUT : Paths.get(args[0]);
        Path parent = output.toAbsolutePath().getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
        Files.writeString(output, generateSql(), StandardCharsets.UTF_8);
        System.out.println("Generated deterministic development data at " + output + ".");
    }

    public static String generateSql() {
        StringBuilder sql = new StringBuilder();
        line(sql, "-- Generated by data.DevelopmentDataGenerator. Do not edit by hand.");
        line(sql, "-- Foundation-only data: stable IDs and representative reserved/GA records.");
        line(sql, "SET NAMES utf8mb4;");
        line(sql, "START TRANSACTION;");
        line(sql, "");
        appendProfiles(sql);
        appendTaxonomyAndVenue(sql);
        appendEventAndPerformances(sql);
        appendPricingAndInventory(sql);
        appendTransactions(sql);
        line(sql, "COMMIT;");
        return sql.toString();
    }

    private static void appendProfiles(StringBuilder sql) {
        line(sql, "INSERT INTO Users");
        line(sql, "    (user_id, name, address, email, date_of_birth, user_role)");
        line(sql, "VALUES");
        line(sql, "    (1001, 'Foundation Organizer', '1 Front Street', 'organizer@foundation.test', '1980-01-15', 'organizer'),");
        line(sql, "    (2001, 'Alice Foundation', '2 Front Street', 'alice@foundation.test', '1990-02-20', 'customer'),");
        line(sql, "    (2002, 'Bob Foundation', '3 Front Street', 'bob@foundation.test', '1992-03-25', 'customer');");
        line(sql, "INSERT INTO Organizer (user_id, user_role) VALUES (1001, 'organizer');");
        line(sql, "INSERT INTO Customer (user_id, user_role) VALUES");
        line(sql, "    (2001, 'customer'), (2002, 'customer');");
        line(sql, "INSERT INTO PaymentInfo");
        line(sql, "    (payment_info_id, customer_id, card_number, card_holder_name, expiry_date, billing_zip)");
        line(sql, "VALUES");
        line(sql, "    (2101, 2001, '4111111111111111', 'Alice Foundation', '2030-12-31', 'M5J 2N8'),");
        line(sql, "    (2102, 2002, '5555555555554444', 'Bob Foundation', '2031-12-31', 'M5J 2N9');");
        line(sql, "");
    }

    private static void appendTaxonomyAndVenue(StringBuilder sql) {
        line(sql, "INSERT INTO Segment (segment_id, segment_name) VALUES (4001, 'Music');");
        line(sql, "INSERT INTO Genre (genre_id, genre_name, segment_id) VALUES (4101, 'Rock', 4001);");
        line(sql, "INSERT INTO ArtistsTeams (artist_id, name, type)");
        line(sql, "VALUES (4201, 'Foundation Band', 'Band');");
        line(sql, "INSERT INTO Venue");
        line(sql, "    (venue_id, name, latitude, longitude, address, city, postal_code, country)");
        line(sql, "VALUES");
        line(sql, "    (3001, 'Foundation Hall', 43.642600, -79.387100, '100 Front Street West', 'Toronto', 'M5J 1E3', 'Canada');");
        line(sql, "INSERT INTO Section (venue_id, section_name, section_type, standing_capacity)");
        line(sql, "VALUES (3001, 'Orchestra', 'reserved', NULL),");
        line(sql, "       (3001, 'General Floor', 'general', 20);");
        line(sql, "INSERT INTO SeatRows (venue_id, section_name, section_type, row_name)");
        line(sql, "VALUES (3001, 'Orchestra', 'reserved', 'A');");
        line(sql, "INSERT INTO Seats (venue_id, section_name, row_name, seat_number) VALUES");
        for (int seat = 1; seat <= 6; seat++) {
            String suffix = seat == 6 ? ";" : ",";
            line(sql, "    (3001, 'Orchestra', 'A', " + seat + ")" + suffix);
        }
        line(sql, "");
    }

    private static void appendEventAndPerformances(StringBuilder sql) {
        line(sql, "INSERT INTO Event");
        line(sql, "    (event_id, title, description, resale_cap_pct, organizer_id, genre_id)");
        line(sql, "VALUES (5001, 'Foundation Concert', 'Deterministic development event', 1.20, 1001, 4101);");
        line(sql, "INSERT INTO BillingOrder (event_id, artist_id, billing_rank)");
        line(sql, "VALUES (5001, 4201, 1);");
        line(sql, "INSERT INTO Performance");
        line(sql, "    (performance_id, event_id, venue_id, date_time, status)");
        line(sql, "VALUES");
        line(sql, "    (6001, 5001, 3001, DATE_ADD(UTC_TIMESTAMP(), INTERVAL 30 DAY), 'scheduled'),");
        line(sql, "    (6002, 5001, 3001, DATE_ADD(UTC_TIMESTAMP(), INTERVAL 45 DAY), 'scheduled'),");
        line(sql, "    (6003, 5001, 3001, DATE_SUB(UTC_TIMESTAMP(), INTERVAL 30 DAY), 'completed');");
        line(sql, "");
    }

    private static void appendPricingAndInventory(StringBuilder sql) {
        line(sql, "INSERT INTO PriceTier (performance_id, tier_code, price) VALUES");
        line(sql, "    (6001, 'P1', 100.00), (6001, 'P2', 60.00),");
        line(sql, "    (6002, 'P1', 110.00), (6002, 'P2', 65.00),");
        line(sql, "    (6003, 'P1', 90.00), (6003, 'P2', 55.00);");
        line(sql, "INSERT INTO SectionTierAssignment");
        line(sql, "    (performance_id, venue_id, section_name, tier_code) VALUES");
        for (int performance = 6001; performance <= 6003; performance++) {
            String suffix = performance == 6003 ? ";" : ",";
            line(sql, "    (" + performance + ", 3001, 'Orchestra', 'P1'),");
            line(sql, "    (" + performance + ", 3001, 'General Floor', 'P2')" + suffix);
        }
        line(sql, "INSERT INTO GeneralAdmissionCapacity");
        line(sql, "    (ga_capacity_id, performance_id, venue_id, section_name, section_type, total_capacity, remaining_capacity)");
        line(sql, "VALUES");
        line(sql, "    (6201, 6001, 3001, 'General Floor', 'general', 20, 20),");
        line(sql, "    (6202, 6002, 3001, 'General Floor', 'general', 20, 19),");
        line(sql, "    (6203, 6003, 3001, 'General Floor', 'general', 20, 20);");
        line(sql, "INSERT INTO PerformanceSeats");
        line(sql, "    (performance_seat_id, performance_id, venue_id, section_name, row_name, seat_number, blocked_status)");
        line(sql, "VALUES");
        for (int performanceOffset = 0; performanceOffset < 3; performanceOffset++) {
            int performanceId = 6001 + performanceOffset;
            int seatIdBase = 6101 + (performanceOffset * 10);
            for (int seat = 1; seat <= 6; seat++) {
                boolean blocked = performanceId == 6001 && seat == 6;
                boolean last = performanceOffset == 2 && seat == 6;
                line(sql, "    (" + (seatIdBase + seat - 1) + ", " + performanceId
                        + ", 3001, 'Orchestra', 'A', " + seat + ", "
                        + (blocked ? "TRUE" : "FALSE") + ")" + (last ? ";" : ","));
            }
        }
        line(sql, "");
    }

    private static void appendTransactions(StringBuilder sql) {
        line(sql, "INSERT INTO Transactions");
        line(sql, "    (transaction_id, customer_id, payment_info_id, payment_card_number,");
        line(sql, "     payment_card_holder_name, payment_expiry_date, payment_billing_zip,");
        line(sql, "     transaction_type, performance_id, listing_id, transaction_date)");
        line(sql, "VALUES");
        line(sql, "    (7001, 2001, 2101, '4111111111111111', 'Alice Foundation', '2030-12-31', 'M5J 2N8', 'purchase', 6001, NULL, DATE_SUB(UTC_TIMESTAMP(), INTERVAL 1 DAY)),");
        line(sql, "    (7002, 2002, 2102, '5555555555554444', 'Bob Foundation', '2031-12-31', 'M5J 2N9', 'purchase', 6002, NULL, DATE_SUB(UTC_TIMESTAMP(), INTERVAL 1 DAY));");
        line(sql, "INSERT INTO Tickets");
        line(sql, "    (ticket_id, purchase_id, performance_id, tier_code, performance_seats_ref,");
        line(sql, "     general_seats_ref, face_value, status)");
        line(sql, "VALUES");
        line(sql, "    (8001, 7001, 6001, 'P1', 6101, NULL, 100.00, 'active'),");
        line(sql, "    (8002, 7002, 6002, 'P2', NULL, 6202, 65.00, 'active');");
        line(sql, "INSERT INTO TicketOwnership");
        line(sql, "    (ownership_id, ticket_id, customer_id, acquired_transaction_id, acquired_listing_id)");
        line(sql, "VALUES (9001, 8001, 2001, 7001, NULL),");
        line(sql, "       (9002, 8002, 2002, 7002, NULL);");
        line(sql, "");
    }

    private static void line(StringBuilder sql, String text) {
        sql.append(text).append(System.lineSeparator());
    }
}
