package data;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

public final class DevelopmentDataGenerator {
    private static final Path DEFAULT_OUTPUT = Paths.get("data", "development-data.sql");

    private static final int ORGANIZER_COUNT = 5;
    private static final int CUSTOMER_COUNT = 100;
    private static final int VENUE_COUNT = 8;
    private static final int EVENT_COUNT = 20;
    private static final int PERFORMANCE_COUNT = 60;
    private static final int PURCHASE_COUNT = 320;
    private static final int TICKETS_PER_PURCHASE = 3;
    private static final int TICKET_COUNT = PURCHASE_COUNT * TICKETS_PER_PURCHASE;

    private static final int FIRST_ORGANIZER_ID = 1001;
    private static final int FIRST_CUSTOMER_ID = 2001;
    private static final int FIRST_PAYMENT_ID = 2101;
    private static final int FIRST_VENUE_ID = 3001;
    private static final int FIRST_EVENT_ID = 5001;
    private static final int FIRST_PERFORMANCE_ID = 6001;

    private static final int SPECIAL_AVAILABLE_PERFORMANCE = 6001;
    private static final int NEAR_DEADLINE_PERFORMANCE = 6002;
    private static final int DOUBLE_RESALE_TICKET = 8007;

    private static final Set<Integer> SOLD_OUT_PERFORMANCES = new LinkedHashSet<>(
            Arrays.asList(6003, 6007, 6019));
    private static final Set<Integer> LOW_SELL_THROUGH_PERFORMANCES = new LinkedHashSet<>(
            Arrays.asList(6004, 6022, 6025));
    private static final Set<Integer> CANCELLED_PERFORMANCES = new LinkedHashSet<>(
            Arrays.asList(6058, 6060));
    private static final Set<Integer> CONFIGURABLE_PERFORMANCES = new LinkedHashSet<>(
            Arrays.asList(6006, 6013));

    private static final String[] ORGANIZER_NAMES = {
        "Northstar Live", "Maple Stage Productions", "Continental Sports Group",
        "City Arts Collective", "Lakeside Events"
    };

    private static final String[] ARTIST_NAMES = {
        "Aurora Avenue", "The Harbour Lights", "Maya Chen", "Northern Echo",
        "City Lights Company", "Jordan Wells", "Toronto Towers", "Montreal Meteors",
        "Vancouver Waves", "New York Comets", "Chicago Crescendos", "Ottawa Owls",
        "Blue Hour Quartet", "Riverstone", "The Weekend Matinee"
    };

    private static final String[] ARTIST_TYPES = {
        "Band", "Band", "Solo Artist", "Band", "Theatre Company",
        "Comedian", "Team", "Team", "Team", "Team", "Orchestra", "Team",
        "Ensemble", "Band", "Theatre Company"
    };

    private static final String[] EVENT_TITLES = {
        "Northern Lights World Tour", "City Lights: The Musical", "Hardwood Rivals",
        "Laughing by the Lake", "Indie Harbour Festival", "Championship Ice Night",
        "Broadway Revisited", "Pop Skyline Live", "Courtside Classic",
        "Rock Across Borders", "Late Night Comedy Club", "Winter Hockey Showcase",
        "Acoustic Stories", "Downtown Musical Gala", "International Basketball Cup",
        "Electric Avenue", "Comedy Passport", "Original Cast Encore",
        "Arena Rock Reunion", "Rivalry on Ice"
    };

    private static final String[] FIRST_NAMES = {
        "Avery", "Jordan", "Taylor", "Morgan", "Casey", "Riley", "Jamie", "Cameron",
        "Quinn", "Parker", "Drew", "Reese", "Skyler", "Rowan", "Emerson", "Finley",
        "Dakota", "Hayden", "Robin", "Sage"
    };

    private static final String[] LAST_NAMES = {
        "Adams", "Bennett", "Chen", "Diaz", "Edwards", "Foster", "Gupta", "Harris",
        "Ivanov", "Johnson", "Khan", "Lewis", "Martin", "Nguyen", "Owens", "Patel",
        "Quintero", "Robinson", "Singh", "Turner"
    };

    private DevelopmentDataGenerator() {
    }

    public static void main(String[] args) throws IOException {
        Path output = args.length == 0 ? DEFAULT_OUTPUT : Paths.get(args[0]);
        Path parent = output.toAbsolutePath().getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
        Files.writeString(output, generateSql(), StandardCharsets.UTF_8);
        System.out.println("Generated deterministic development data at " + output + ".");
    }

    public static String generateSql() {
        Dataset dataset = buildDataset();
        validateDataset(dataset);

        StringBuilder sql = new StringBuilder();
        line(sql, "-- Generated by data.DevelopmentDataGenerator. Do not edit by hand.");
        line(sql, "-- Complete PDF-compliant sample data with stable IDs and relative UTC dates.");
        line(sql, "SET NAMES utf8mb4;");
        line(sql, "START TRANSACTION;");
        line(sql, "");
        appendProfiles(sql);
        appendTaxonomy(sql);
        appendVenues(sql, dataset);
        appendEvents(sql, dataset);
        appendPerformancesAndInventory(sql, dataset);
        appendPurchasesAndTickets(sql, dataset);
        appendCancellations(sql, dataset);
        appendResaleMarket(sql, dataset);
        appendCustomerRestrictions(sql);
        appendReviews(sql, dataset);
        line(sql, "COMMIT;");
        line(sql, "");
        appendCountChecks(sql);
        return sql.toString();
    }

    private static Dataset buildDataset() {
        Dataset dataset = new Dataset();
        dataset.venues.addAll(buildVenues());
        dataset.events.addAll(buildEvents());
        dataset.performances.addAll(buildPerformances());
        initializePricingAndInventory(dataset);
        createPurchases(dataset);
        createCancellations(dataset);
        createResaleMarket(dataset);
        createReviews(dataset);
        return dataset;
    }

    private static List<VenueSpec> buildVenues() {
        List<VenueSpec> venues = new ArrayList<>();

        venues.add(venue(3001, "Harbourfront Arena", "43.643500", "-79.379100",
                "40 Bay Street", "Toronto", "M5J 2X2", "Canada",
                reserved("Orchestra", new String[] {"A", "B"}, 12),
                reserved("Balcony", new String[] {"C", "D"}, 9),
                general("General Floor", 60)));
        venues.add(venue(3002, "Union Theatre", "43.645300", "-79.381500",
                "65 Front Street West", "Toronto", "M5J 1E6", "Canada",
                reserved("Orchestra", new String[] {"A", "B", "C"}, 10),
                reserved("Mezzanine", new String[] {"D", "E"}, 9),
                reserved("Balcony", new String[] {"F", "G"}, 9)));
        venues.add(venue(3003, "Lakeshore Pavilion", "43.638800", "-79.381700",
                "235 Queens Quay West", "Toronto", "M5J 2G8", "Canada",
                reserved("Lower Bowl", new String[] {"A", "B"}, 12),
                reserved("Upper Bowl", new String[] {"C", "D"}, 9),
                general("General Admission", 60)));
        venues.add(venue(3004, "Pacific Centre Stadium", "49.276700", "-123.111900",
                "777 Pacific Boulevard", "Vancouver", "V6B 4Y8", "Canada",
                reserved("Lower Bowl", new String[] {"A", "B", "C"}, 12),
                reserved("Upper Bowl", new String[] {"D", "E", "F"}, 10),
                reserved("Club Level", new String[] {"G", "H"}, 9)));
        venues.add(venue(3005, "Montreal Central Arena", "45.496100", "-73.569300",
                "1909 Avenue des Canadiens-de-Montreal", "Montreal", "H3B 5E8", "Canada",
                reserved("Floor", new String[] {"A", "B"}, 12),
                reserved("Balcony", new String[] {"C", "D"}, 9),
                general("General Admission", 48)));
        venues.add(venue(3006, "Capital Arts Centre", "45.423300", "-75.693100",
                "1 Elgin Street", "Ottawa", "K1P 5W1", "Canada",
                reserved("Orchestra", new String[] {"A", "B", "C"}, 10),
                reserved("Mezzanine", new String[] {"D", "E"}, 9),
                reserved("Balcony", new String[] {"F", "G"}, 6)));
        venues.add(venue(3007, "Manhattan Event Garden", "40.750500", "-73.993400",
                "4 Pennsylvania Plaza", "New York", "10001", "United States",
                reserved("Lower Bowl", new String[] {"A", "B", "C"}, 12),
                reserved("Upper Bowl", new String[] {"D", "E", "F"}, 10),
                general("General Admission", 60)));
        venues.add(venue(3008, "Chicago Auditorium Hall", "41.875800", "-87.625800",
                "50 East Ida B. Wells Drive", "Chicago", "60605", "United States",
                reserved("Main Floor", new String[] {"A", "B", "C"}, 10),
                reserved("Balcony", new String[] {"D", "E"}, 9),
                general("Standing Room", 42)));

        return venues;
    }

    private static List<EventSpec> buildEvents() {
        int[] genreIds = {
            4101, 4103, 4105, 4104, 4102, 4106, 4103, 4102, 4105, 4101,
            4104, 4106, 4102, 4103, 4105, 4101, 4104, 4103, 4101, 4106
        };
        List<EventSpec> events = new ArrayList<>();
        for (int index = 0; index < EVENT_COUNT; index++) {
            int eventId = FIRST_EVENT_ID + index;
            int organizerId = FIRST_ORGANIZER_ID + (index % ORGANIZER_COUNT);
            int capHundredths = 115 + ((index % 4) * 5);
            List<Integer> artists = new ArrayList<>();
            artists.add(4201 + (index % ARTIST_NAMES.length));
            if (index % 3 == 0) {
                artists.add(4201 + ((index + 5) % ARTIST_NAMES.length));
            }
            if (index % 7 == 0) {
                artists.add(4201 + ((index + 10) % ARTIST_NAMES.length));
            }
            events.add(new EventSpec(eventId, EVENT_TITLES[index],
                    "A fictional MyTix event created for deterministic testing and reporting.",
                    capHundredths, organizerId, genreIds[index], artists));
        }
        return events;
    }

    private static List<PerformanceSpec> buildPerformances() {
        List<PerformanceSpec> performances = new ArrayList<>();

        performances.add(performance(6001, 5001, 3001, 30, "scheduled"));
        performances.add(performance(6002, 5001, 3001, 5, "scheduled"));
        performances.add(performance(6003, 5001, 3004, -30, "completed"));
        performances.add(performance(6004, 5001, 3005, -90, "completed"));
        performances.add(performance(6005, 5001, 3007, -150, "completed"));
        performances.add(performance(6006, 5001, 3003, 90, "scheduled"));

        for (int localIndex = 0; localIndex < 12; localIndex++) {
            int performanceId = 6007 + localIndex;
            int offset = localIndex < 6 ? -(20 + (localIndex * 30)) : 15 + ((localIndex - 6) * 20);
            if (performanceId == 6007) {
                offset = -120;
            }
            performances.add(performance(performanceId, 5002, 3002, offset,
                    offset < 0 ? "completed" : "scheduled"));
        }

        int performanceId = 6019;
        for (int eventId = 5003; eventId <= 5020; eventId++) {
            int performanceTotal = eventId <= 5008 ? 3 : 2;
            for (int localIndex = 0; localIndex < performanceTotal; localIndex++) {
                int venueId = 3001 + ((eventId - 5003 + localIndex) % VENUE_COUNT);
                int offset;
                String status;
                if (localIndex == 0) {
                    offset = -(25 + ((eventId - 5003) * 14));
                    status = "completed";
                } else if (localIndex == 1) {
                    offset = 20 + ((eventId - 5003) * 9);
                    status = "scheduled";
                } else {
                    offset = -(120 + ((eventId - 5003) * 12));
                    status = "completed";
                }

                if (performanceId == 6019) {
                    venueId = 3005;
                    offset = -210;
                } else if (performanceId == 6022) {
                    venueId = 3006;
                    offset = -160;
                } else if (performanceId == 6025) {
                    venueId = 3007;
                    offset = -230;
                }

                if (performanceId == 6058 || performanceId == 6060) {
                    status = "cancelled";
                    offset = performanceId == 6058 ? 70 : 100;
                }

                PerformanceSpec spec = performance(performanceId, eventId, venueId, offset, status);
                if ("cancelled".equals(status)) {
                    spec.cancellationDaysAgo = performanceId == 6058 ? 20 : 45;
                    spec.cancellationReason = performanceId == 6058
                            ? "Tour routing conflict" : "Venue maintenance closure";
                }
                performances.add(spec);
                performanceId++;
            }
        }

        return performances;
    }

    private static void initializePricingAndInventory(Dataset dataset) {
        int nextSeatId = 610001;
        int nextGaId = 620001;

        for (PerformanceSpec performance : dataset.performances) {
            VenueSpec venue = venueById(dataset, performance.venueId);
            int eventOffset = performance.eventId - FIRST_EVENT_ID;
            int basePrice = 6500 + ((eventOffset % 5) * 900) + ((performance.id % 4) * 250);
            performance.tierPrices.put("P1", basePrice + 3500);
            performance.tierPrices.put("P2", basePrice + 1200);
            performance.tierPrices.put("P3", basePrice - 800);

            if (performance.id == 6001) {
                performance.tierPrices.put("P1", 12000);
                performance.tierPrices.put("P2", 8000);
                performance.tierPrices.put("P3", 5000);
            } else if (performance.id == 6002) {
                performance.tierPrices.put("P1", 13500);
                performance.tierPrices.put("P2", 9000);
                performance.tierPrices.put("P3", 5500);
            }

            for (int sectionIndex = 0; sectionIndex < venue.sections.size(); sectionIndex++) {
                SectionSpec section = venue.sections.get(sectionIndex);
                String tierCode = "P" + (sectionIndex + 1);
                if (performance.id == 6002 && sectionIndex < 2) {
                    tierCode = sectionIndex == 0 ? "P2" : "P1";
                }
                performance.sectionTiers.put(section.name, tierCode);

                if (section.generalAdmission) {
                    GaInventory ga = new GaInventory(nextGaId++, performance.id, venue.id,
                            section.name, section.capacity);
                    dataset.gaInventory.add(ga);
                    dataset.gaByPerformance.computeIfAbsent(performance.id, ignored -> new ArrayList<>()).add(ga);
                } else {
                    for (String rowName : section.rowNames) {
                        for (int seatNumber = 1; seatNumber <= section.seatsPerRow; seatNumber++) {
                            boolean blocked = shouldBlockSeat(performance.id, section, rowName, seatNumber);
                            SeatInventory seat = new SeatInventory(nextSeatId++, performance.id, venue.id,
                                    section.name, rowName, seatNumber, blocked);
                            dataset.seatInventory.add(seat);
                            dataset.seatsByPerformance.computeIfAbsent(performance.id,
                                    ignored -> new ArrayList<>()).add(seat);
                        }
                    }
                }
            }
        }
    }

    private static boolean shouldBlockSeat(int performanceId, SectionSpec section,
            String rowName, int seatNumber) {
        if (SOLD_OUT_PERFORMANCES.contains(performanceId)) {
            return false;
        }
        if (performanceId == SPECIAL_AVAILABLE_PERFORMANCE
                && "Orchestra".equals(section.name)) {
            return ("A".equals(rowName) && seatNumber == 12)
                    || ("B".equals(rowName) && seatNumber % 2 == 0);
        }
        return performanceId % 9 == 0
                && seatNumber == section.seatsPerRow
                && rowName.equals(section.rowNames[0]);
    }

    private static void createPurchases(Dataset dataset) {
        Map<Integer, Integer> orderCounts = buildOrderCounts(dataset);
        Map<Integer, Integer> createdByPerformance = new HashMap<>();

        dataset.nextTicketId = 8003;
        createPurchase(dataset, 7001, 2001, 6001, 0, new int[] {8001, 8003, 8004});
        createdByPerformance.put(6001, 1);
        dataset.nextTicketId = 8005;
        createPurchase(dataset, 7002, 2002, 6002, 0, new int[] {8002, 8005, 8006});
        createdByPerformance.put(6002, 1);
        dataset.nextTicketId = 8007;

        int nextPurchaseId = 7003;
        int regularCustomerOffset = 0;
        for (PerformanceSpec performance : dataset.performances) {
            int target = orderCounts.get(performance.id);
            int alreadyCreated = createdByPerformance.getOrDefault(performance.id, 0);
            for (int performanceOrderIndex = alreadyCreated;
                    performanceOrderIndex < target; performanceOrderIndex++) {
                int customerId;
                if (performance.id == 6003 && performanceOrderIndex < 3) {
                    customerId = 2001;
                } else if (performance.id == 6003 && performanceOrderIndex < 6) {
                    customerId = 2002;
                } else {
                    customerId = 2003 + (regularCustomerOffset % 98);
                    regularCustomerOffset++;
                }
                int[] ticketIds = {
                    dataset.nextTicketId++, dataset.nextTicketId++, dataset.nextTicketId++
                };
                createPurchase(dataset, nextPurchaseId++, customerId, performance.id,
                        performanceOrderIndex, ticketIds);
            }
        }
    }

    private static Map<Integer, Integer> buildOrderCounts(Dataset dataset) {
        Map<Integer, Integer> orderCounts = new LinkedHashMap<>();
        orderCounts.put(6001, 4);
        orderCounts.put(6002, 5);
        orderCounts.put(6003, venueCapacity(venueById(dataset, performanceById(dataset, 6003).venueId)) / 3);
        orderCounts.put(6007, venueCapacity(venueById(dataset, performanceById(dataset, 6007).venueId)) / 3);
        orderCounts.put(6019, venueCapacity(venueById(dataset, performanceById(dataset, 6019).venueId)) / 3);
        orderCounts.put(6004, 2);
        orderCounts.put(6022, 2);
        orderCounts.put(6025, 3);
        orderCounts.put(6058, 5);
        orderCounts.put(6060, 5);
        for (int performanceId : CONFIGURABLE_PERFORMANCES) {
            orderCounts.put(performanceId, 0);
        }

        int assigned = orderCounts.values().stream().mapToInt(Integer::intValue).sum();
        int remainingWithFive = PURCHASE_COUNT - assigned - ((PERFORMANCE_COUNT - orderCounts.size()) * 4);
        for (PerformanceSpec performance : dataset.performances) {
            if (!orderCounts.containsKey(performance.id)) {
                orderCounts.put(performance.id, remainingWithFive > 0 ? 5 : 4);
                if (remainingWithFive > 0) {
                    remainingWithFive--;
                }
            }
        }
        require(orderCounts.values().stream().mapToInt(Integer::intValue).sum() == PURCHASE_COUNT,
                "Purchase allocation must total exactly " + PURCHASE_COUNT + ".");
        return orderCounts;
    }

    private static void createPurchase(Dataset dataset, int purchaseId, int customerId,
            int performanceId, int performanceOrderIndex, int[] ticketIds) {
        PerformanceSpec performance = performanceById(dataset, performanceId);
        String transactionDate = purchaseDateExpression(performance, purchaseId);
        TransactionSpec transaction = TransactionSpec.purchase(purchaseId, customerId,
                paymentId(customerId), performanceId, transactionDate);
        dataset.purchases.add(transaction);

        for (int ticketIndex = 0; ticketIndex < ticketIds.length; ticketIndex++) {
            TicketSpec ticket = allocateTicket(dataset, performance, purchaseId, customerId,
                    ticketIds[ticketIndex], performanceOrderIndex, ticketIndex);
            dataset.tickets.add(ticket);
        }
    }

    private static TicketSpec allocateTicket(Dataset dataset, PerformanceSpec performance,
            int purchaseId, int customerId, int ticketId, int performanceOrderIndex,
            int ticketIndex) {
        if (performance.id == 6001) {
            if (performanceOrderIndex == 0) {
                return allocateSpecificSeat(dataset, performance, purchaseId, customerId, ticketId,
                        "Orchestra", "A", 5 + ticketIndex);
            }
            int balconySeat = ((performanceOrderIndex - 1) * TICKETS_PER_PURCHASE) + ticketIndex + 1;
            return allocateSpecificSeat(dataset, performance, purchaseId, customerId, ticketId,
                    "Balcony", "C", balconySeat);
        }
        if (performance.id == 6002 && performanceOrderIndex == 0) {
            return allocateGeneralAdmission(dataset, performance, purchaseId, customerId, ticketId);
        }

        List<SeatInventory> seats = dataset.seatsByPerformance.getOrDefault(
                performance.id, Collections.emptyList());
        for (SeatInventory seat : seats) {
            if (!seat.blocked && !seat.allocated) {
                seat.allocated = true;
                String tierCode = performance.sectionTiers.get(seat.sectionName);
                return TicketSpec.reserved(ticketId, purchaseId, performance.id, customerId,
                        tierCode, seat.id, performance.tierPrices.get(tierCode));
            }
        }
        return allocateGeneralAdmission(dataset, performance, purchaseId, customerId, ticketId);
    }

    private static TicketSpec allocateSpecificSeat(Dataset dataset, PerformanceSpec performance,
            int purchaseId, int customerId, int ticketId, String sectionName,
            String rowName, int seatNumber) {
        for (SeatInventory seat : dataset.seatsByPerformance.get(performance.id)) {
            if (seat.sectionName.equals(sectionName) && seat.rowName.equals(rowName)
                    && seat.seatNumber == seatNumber) {
                require(!seat.blocked && !seat.allocated,
                        "Requested deterministic reserved seat is unavailable.");
                seat.allocated = true;
                String tierCode = performance.sectionTiers.get(sectionName);
                return TicketSpec.reserved(ticketId, purchaseId, performance.id, customerId,
                        tierCode, seat.id, performance.tierPrices.get(tierCode));
            }
        }
        throw new IllegalStateException("Deterministic reserved seat was not generated.");
    }

    private static TicketSpec allocateGeneralAdmission(Dataset dataset, PerformanceSpec performance,
            int purchaseId, int customerId, int ticketId) {
        for (GaInventory ga : dataset.gaByPerformance.getOrDefault(
                performance.id, Collections.emptyList())) {
            if (ga.allocatedCount < ga.totalCapacity) {
                ga.allocatedCount++;
                ga.activeSoldCount++;
                String tierCode = performance.sectionTiers.get(ga.sectionName);
                return TicketSpec.general(ticketId, purchaseId, performance.id, customerId,
                        tierCode, ga.id, performance.tierPrices.get(tierCode));
            }
        }
        throw new IllegalStateException("Performance " + performance.id
                + " does not have enough inventory for the deterministic ticket allocation.");
    }

    private static void createCancellations(Dataset dataset) {
        int nextCancellationId = 11001;
        int nextRefundId = 12001;

        for (TicketSpec ticket : dataset.tickets) {
            if (CANCELLED_PERFORMANCES.contains(ticket.performanceId)) {
                PerformanceSpec performance = performanceById(dataset, ticket.performanceId);
                EventSpec event = eventById(dataset, performance.eventId);
                String cancellationDate = daysAgoExpression(performance.cancellationDaysAgo);
                cancelTicket(dataset, ticket, nextCancellationId++, nextRefundId++,
                        event.organizerId, cancellationDate, "Organizer cancelled the performance");
            }
        }

        Set<Integer> cancellingCustomers = new HashSet<>();
        int customerCancellationIndex = 0;
        for (TicketSpec ticket : dataset.tickets) {
            if (customerCancellationIndex >= 12) {
                break;
            }
            PerformanceSpec performance = performanceById(dataset, ticket.performanceId);
            if (!"scheduled".equals(performance.status) || performance.offsetDays <= 7
                    || ticket.customerId < 2003 || ticket.id == DOUBLE_RESALE_TICKET
                    || ticket.performanceId == SPECIAL_AVAILABLE_PERFORMANCE
                    || cancellingCustomers.contains(ticket.customerId)) {
                continue;
            }
            String cancellationDate = daysAgoExpression(2 + customerCancellationIndex);
            cancelTicket(dataset, ticket, nextCancellationId++, nextRefundId++, ticket.customerId,
                    cancellationDate, "Customer cancelled before the seven-day deadline");
            cancellingCustomers.add(ticket.customerId);
            customerCancellationIndex++;
        }
        require(customerCancellationIndex == 12,
                "The dataset must contain twelve customer-cancelled tickets.");
    }

    private static void cancelTicket(Dataset dataset, TicketSpec ticket, int cancellationId,
            int refundId, int cancelledByUserId, String cancellationDate, String reason) {
        require("active".equals(ticket.status), "A deterministic ticket cannot be cancelled twice.");
        ticket.status = "cancelled";
        if (ticket.gaCapacityId != null) {
            GaInventory ga = gaById(dataset, ticket.gaCapacityId);
            ga.activeSoldCount--;
        }
        dataset.cancellations.add(new CancellationSpec(cancellationId, refundId, ticket.id,
                initialOwnershipId(ticket.id), cancelledByUserId, cancellationDate,
                reason, ticket.faceValueCents));
    }

    private static void createResaleMarket(Dataset dataset) {
        createScalperListings(dataset, 2001, 2050);
        createScalperListings(dataset, 2002, 2060);

        TicketSpec ticket = ticketById(dataset, DOUBLE_RESALE_TICKET);
        require("active".equals(ticket.status), "The twice-resold ticket must remain active.");
        ListingSpec firstSale = createListing(dataset, ticket, initialOwnershipId(ticket.id),
                ticket.customerId, "sold", true, 2099, 18, 14);
        createListing(dataset, ticket, firstSale.sale.newOwnershipId, 2099,
                "sold", false, 2100, 10, 6);
    }

    private static void createScalperListings(Dataset dataset, int customerId, int buyerBase) {
        List<TicketSpec> past = new ArrayList<>();
        List<TicketSpec> future = new ArrayList<>();
        for (TicketSpec ticket : dataset.tickets) {
            if (ticket.customerId != customerId || !"active".equals(ticket.status)) {
                continue;
            }
            PerformanceSpec performance = performanceById(dataset, ticket.performanceId);
            if (performance.offsetDays < 0) {
                past.add(ticket);
            } else if ("scheduled".equals(performance.status)) {
                future.add(ticket);
            }
        }
        require(past.size() >= 5 && future.size() >= 2,
                "Each deterministic scalper needs past and future tickets.");

        List<TicketSpec> selected = new ArrayList<>();
        selected.addAll(past.subList(0, 5));
        selected.addAll(future.subList(0, 2));
        for (int index = 0; index < selected.size(); index++) {
            String status = index < 3 ? "sold" : index < 5 ? "withdrawn" : "active";
            boolean exactlyAtCap = index == 0 || index == 5;
            int buyerId = buyerBase + index;
            PerformanceSpec performance = performanceById(dataset, selected.get(index).performanceId);
            int listedDaysAgo = performance.offsetDays < 0 ? 45 - index : 12 - index;
            int soldDaysAgo = listedDaysAgo - 5;
            createListing(dataset, selected.get(index),
                    initialOwnershipId(selected.get(index).id), customerId, status,
                    exactlyAtCap, buyerId, listedDaysAgo, soldDaysAgo);
        }
    }

    private static ListingSpec createListing(Dataset dataset, TicketSpec ticket,
            int sellerOwnershipId, int sellerCustomerId, String status, boolean exactlyAtCap,
            int buyerId, int listedDaysAgo, int soldDaysAgo) {
        EventSpec event = eventById(dataset,
                performanceById(dataset, ticket.performanceId).eventId);
        int capPrice = (ticket.faceValueCents * event.resaleCapHundredths) / 100;
        int listingPrice = exactlyAtCap ? capPrice
                : Math.min(capPrice, (ticket.faceValueCents * 110) / 100);
        ListingSpec listing = new ListingSpec(dataset.nextListingId++, ticket.id,
                sellerOwnershipId, listingPrice, capPrice, status,
                daysAgoExpression(listedDaysAgo));
        dataset.listings.add(listing);
        dataset.listedTicketIds.add(ticket.id);

        if ("sold".equals(status)) {
            require(buyerId != sellerCustomerId, "A resale buyer must differ from the seller.");
            int transactionId = dataset.nextResaleTransactionId++;
            int ownershipId = dataset.nextTransferOwnershipId++;
            String saleDate = daysAgoExpression(soldDaysAgo);
            TransactionSpec transaction = TransactionSpec.resale(transactionId, buyerId,
                    paymentId(buyerId), listing.id, saleDate);
            listing.sale = new SaleSpec(transaction, sellerOwnershipId, ownershipId,
                    buyerId, saleDate);
        }
        return listing;
    }

    private static void createReviews(Dataset dataset) {
        int reviewSequence = 0;
        for (int eventId = 5001; eventId <= 5010; eventId++) {
            Set<String> customerPerformancePairs = new HashSet<>();
            int reviewsForEvent = 0;
            for (TicketSpec ticket : dataset.tickets) {
                PerformanceSpec performance = performanceById(dataset, ticket.performanceId);
                if (performance.eventId != eventId || !"completed".equals(performance.status)
                        || !"active".equals(ticket.status)
                        || dataset.listedTicketIds.contains(ticket.id)) {
                    continue;
                }
                String pair = ticket.customerId + ":" + ticket.performanceId;
                if (!customerPerformancePairs.add(pair)) {
                    continue;
                }
                String comment = reviewComment(reviewSequence++);
                int eventRating = 3 + (reviewsForEvent % 3);
                int venueRating = 3 + ((reviewsForEvent + 1) % 3);
                int reviewDaysAgo = Math.max(1, (-performance.offsetDays) - 2);
                dataset.reviews.add(new ReviewSpec(ticket.customerId, performance.id,
                        comment, eventRating, venueRating, daysAgoExpression(reviewDaysAgo)));
                reviewsForEvent++;
                if (reviewsForEvent == 3) {
                    break;
                }
            }
            require(reviewsForEvent == 3,
                    "Each of the ten reviewed events must have three reviews.");
        }
    }

    private static String reviewComment(int sequence) {
        String[] openings = {
            "The live performance created a warm atmosphere and the sound design stayed clear throughout the evening.",
            "The stage production used thoughtful lighting and the lead performers held the audience's attention.",
            "The event pacing felt energetic and the crowd response made the headline moments memorable."
        };
        String[] middles = {
            "The venue staff gave helpful directions, and the seating area was comfortable and easy to reach.",
            "The main floor had a strong view of the stage, while the entry process moved at a steady pace.",
            "The musical arrangements, audience energy, and venue layout worked especially well together."
        };
        return openings[sequence % openings.length] + " "
                + middles[(sequence / openings.length) % middles.length] + " "
                + "The overall experience offered memorable music, friendly service, and a welcoming crowd.";
    }

    private static void validateDataset(Dataset dataset) {
        require(dataset.venues.size() == VENUE_COUNT, "Exactly eight venues are required.");
        Set<String> cities = new HashSet<>();
        Set<String> countries = new HashSet<>();
        int mixedVenues = 0;
        for (VenueSpec venue : dataset.venues) {
            cities.add(venue.city);
            countries.add(venue.country);
            require(venue.sections.size() >= 3, "Every venue must have several sections.");
            boolean reserved = venue.sections.stream().anyMatch(section -> !section.generalAdmission);
            boolean general = venue.sections.stream().anyMatch(section -> section.generalAdmission);
            if (reserved && general) {
                mixedVenues++;
            }
        }
        require(cities.size() >= 4 && countries.size() >= 2 && mixedVenues >= 2,
                "Venue geography and seating minimums are not satisfied.");
        require(dataset.venues.get(0).postalCode.startsWith("M5J")
                        && dataset.venues.get(1).postalCode.startsWith("M5J")
                        && dataset.venues.get(2).postalCode.startsWith("M5J"),
                "Three nearby Toronto venues must share the M5J postal area.");

        require(dataset.events.size() == EVENT_COUNT, "Exactly twenty events are required.");
        require(dataset.events.stream().map(event -> event.organizerId).distinct().count()
                        >= ORGANIZER_COUNT,
                "At least five organizers must manage events.");
        require(dataset.events.stream().anyMatch(event -> event.artistIds.size() > 1),
                "At least one event must have multiple billed artists.");
        require(dataset.performances.size() == PERFORMANCE_COUNT,
                "Exactly sixty performances are required.");
        require(dataset.performances.stream().anyMatch(performance -> performance.offsetDays < 0)
                        && dataset.performances.stream().anyMatch(performance -> performance.offsetDays > 0),
                "Both past and upcoming performances are required.");
        require(dataset.performances.stream().filter(performance -> performance.eventId == 5001)
                        .map(performance -> performance.venueId).distinct().count() >= 4,
                "The touring event must visit several venues.");
        require(dataset.performances.stream().filter(performance -> performance.eventId == 5002
                        && performance.venueId == 3002).count() == 12,
                "The theatre event must have many performances at one venue.");

        for (PerformanceSpec performance : dataset.performances) {
            require(performance.tierPrices.size() >= 2,
                    "Every performance must have at least two price tiers.");
            require(performance.sectionTiers.size()
                            == venueById(dataset, performance.venueId).sections.size(),
                    "Every performance section must have exactly one tier assignment.");
        }
        PerformanceSpec firstSetup = performanceById(dataset, 6001);
        PerformanceSpec secondSetup = performanceById(dataset, 6002);
        require(!firstSetup.tierPrices.equals(secondSetup.tierPrices)
                        && !firstSetup.sectionTiers.equals(secondSetup.sectionTiers),
                "The two Toronto performances must use different prices and tier mappings.");
        require(dataset.seatInventory.stream().anyMatch(seat -> seat.blocked),
                "Performance-specific blocked seats are required.");

        for (int performanceId : CONFIGURABLE_PERFORMANCES) {
            PerformanceSpec performance = performanceById(dataset, performanceId);
            require("scheduled".equals(performance.status) && performance.offsetDays > 0,
                    "Configurable performance " + performanceId
                            + " must be scheduled in the future.");
            require(dataset.tickets.stream().noneMatch(ticket ->
                            ticket.performanceId == performanceId),
                    "Configurable performance " + performanceId
                            + " must not have sold tickets.");
        }

        require(dataset.purchases.size() == PURCHASE_COUNT,
                "Exactly 320 purchase orders are required.");
        require(dataset.tickets.size() == TICKET_COUNT,
                "Exactly 960 tickets are required.");
        Map<Integer, Integer> ticketsByPurchase = new HashMap<>();
        for (TicketSpec ticket : dataset.tickets) {
            ticketsByPurchase.merge(ticket.purchaseId, 1, Integer::sum);
        }
        require(ticketsByPurchase.values().stream().allMatch(count -> count == TICKETS_PER_PURCHASE),
                "Every deterministic purchase must contain three tickets.");

        validateSalesExamples(dataset);
        validateAvailabilityExamples(dataset);

        require(dataset.cancellations.size() >= 40,
                "Customer and organizer cancellations with refunds are required.");
        require(dataset.cancellations.stream().map(cancellation -> cancellation.cancelledByUserId)
                        .filter(userId -> userId >= FIRST_CUSTOMER_ID).distinct().count() >= 5,
                "Several different customers must have cancellation records.");
        require(CANCELLED_PERFORMANCES.stream().allMatch(performanceId ->
                        "cancelled".equals(performanceById(dataset, performanceId).status)),
                "Two organizer-cancelled performances are required.");

        require(dataset.listings.stream().anyMatch(listing -> "active".equals(listing.status))
                        && dataset.listings.stream().anyMatch(listing -> "withdrawn".equals(listing.status))
                        && dataset.listings.stream().anyMatch(listing -> "sold".equals(listing.status)),
                "Active, withdrawn, and sold resale listings are required.");
        require(dataset.listings.stream().filter(listing -> listing.listingPriceCents
                        == listing.capPriceCents).count() >= 2,
                "Several listings must be priced exactly at the resale cap.");
        require(dataset.listings.stream().filter(listing -> listing.ticketId == DOUBLE_RESALE_TICKET
                        && "sold".equals(listing.status)).count() == 2,
                "One ticket must change owners twice.");
        validateScalper(dataset, 2001);
        validateScalper(dataset, 2002);

        Map<Integer, Long> reviewsByEvent = new HashMap<>();
        for (ReviewSpec review : dataset.reviews) {
            int eventId = performanceById(dataset, review.performanceId).eventId;
            reviewsByEvent.merge(eventId, 1L, Long::sum);
            require(review.comment.split("\\.").length >= 3,
                    "Review comments must contain several sentences.");
        }
        require(reviewsByEvent.size() >= 10
                        && reviewsByEvent.values().stream().allMatch(count -> count >= 3),
                "At least ten events must have several reviews each.");
    }

    private static void validateSalesExamples(Dataset dataset) {
        for (int performanceId : SOLD_OUT_PERFORMANCES) {
            PerformanceSpec performance = performanceById(dataset, performanceId);
            int activeTickets = (int) dataset.tickets.stream()
                    .filter(ticket -> ticket.performanceId == performanceId
                            && "active".equals(ticket.status)).count();
            require(activeTickets == sellableCapacity(dataset, performanceId),
                    "Sold-out performance " + performanceId + " must use all sellable capacity.");
        }
        for (int performanceId : LOW_SELL_THROUGH_PERFORMANCES) {
            int activeTickets = (int) dataset.tickets.stream()
                    .filter(ticket -> ticket.performanceId == performanceId
                            && "active".equals(ticket.status)).count();
            require(activeTickets * 4 < sellableCapacity(dataset, performanceId),
                    "Low-sell-through performance " + performanceId + " must remain below 25%.");
        }
        validatePerformanceSpread(dataset, SOLD_OUT_PERFORMANCES, "Sold-out");
        validatePerformanceSpread(dataset, LOW_SELL_THROUGH_PERFORMANCES,
                "Low-sell-through");

        Map<Integer, Set<String>> customerCities = new HashMap<>();
        Map<Integer, Integer> customerOrders = new HashMap<>();
        for (TransactionSpec purchase : dataset.purchases) {
            PerformanceSpec performance = performanceById(dataset, purchase.performanceId);
            String city = venueById(dataset, performance.venueId).city;
            customerCities.computeIfAbsent(purchase.customerId, ignored -> new HashSet<>()).add(city);
            customerOrders.merge(purchase.customerId, 1, Integer::sum);
        }
        long multiCityRepeatCustomers = customerOrders.entrySet().stream()
                .filter(entry -> entry.getValue() >= 2
                        && customerCities.get(entry.getKey()).size() >= 2).count();
        require(multiCityRepeatCustomers >= 5,
                "Several customers need repeat orders in multiple cities.");
    }

    private static void validatePerformanceSpread(Dataset dataset,
            Set<Integer> performanceIds, String label) {
        Set<String> cities = new HashSet<>();
        Set<Integer> monthBuckets = new HashSet<>();
        for (int performanceId : performanceIds) {
            PerformanceSpec performance = performanceById(dataset, performanceId);
            cities.add(venueById(dataset, performance.venueId).city);
            monthBuckets.add(Math.abs(performance.offsetDays) / 30);
        }
        require(cities.size() >= 3 && monthBuckets.size() >= 3,
                label + " examples must span at least three cities and months.");
    }

    private static void validateAvailabilityExamples(Dataset dataset) {
        Set<Integer> activeReservedSeatIds = new HashSet<>();
        for (TicketSpec ticket : dataset.tickets) {
            if ("active".equals(ticket.status) && ticket.performanceSeatId != null) {
                activeReservedSeatIds.add(ticket.performanceSeatId);
            }
        }

        for (int seatNumber = 1; seatNumber <= 4; seatNumber++) {
            SeatInventory seat = findSeat(dataset, SPECIAL_AVAILABLE_PERFORMANCE,
                    "Orchestra", "A", seatNumber);
            require(!seat.blocked && !activeReservedSeatIds.contains(seat.id),
                    "Orchestra row A seats 1-4 must remain consecutively available.");
        }

        List<Integer> rowBAvailable = new ArrayList<>();
        for (SeatInventory seat : dataset.seatsByPerformance.get(SPECIAL_AVAILABLE_PERFORMANCE)) {
            if ("Orchestra".equals(seat.sectionName) && "B".equals(seat.rowName)
                    && !seat.blocked && !activeReservedSeatIds.contains(seat.id)) {
                rowBAvailable.add(seat.seatNumber);
            }
        }
        Collections.sort(rowBAvailable);
        require(rowBAvailable.size() >= 2, "The nonconsecutive example row needs available seats.");
        for (int index = 1; index < rowBAvailable.size(); index++) {
            require(rowBAvailable.get(index) - rowBAvailable.get(index - 1) > 1,
                    "Only nonconsecutive seats may remain in Orchestra row B.");
        }

        require(dataset.gaByPerformance.get(SPECIAL_AVAILABLE_PERFORMANCE).stream()
                        .anyMatch(ga -> ga.activeSoldCount < ga.totalCapacity),
                "The future availability example needs remaining general admission capacity.");
        require(dataset.tickets.stream().anyMatch(ticket -> ticket.performanceId
                        == NEAR_DEADLINE_PERFORMANCE && "active".equals(ticket.status)),
                "The performance within seven days must have sold tickets.");

        PerformanceSpec special = performanceById(dataset, SPECIAL_AVAILABLE_PERFORMANCE);
        Set<String> soldTiers = new HashSet<>();
        for (TicketSpec ticket : dataset.tickets) {
            if (ticket.performanceId == special.id) {
                soldTiers.add(ticket.tierCode);
            }
        }
        require(soldTiers.contains("P1") && soldTiers.contains("P2") && !soldTiers.contains("P3"),
                "The future price-change example needs sold and unsold tiers.");
    }

    private static void validateScalper(Dataset dataset, int customerId) {
        long purchasedTickets = dataset.tickets.stream()
                .filter(ticket -> ticket.customerId == customerId).count();
        long listings = dataset.listings.stream()
                .filter(listing -> ticketById(dataset, listing.ticketId).customerId == customerId)
                .count();
        require(purchasedTickets >= 10 && listings * 2 > purchasedTickets,
                "Customer " + customerId + " must satisfy the possible-scalper threshold.");
    }

    private static void appendProfiles(StringBuilder sql) {
        List<String> userRows = new ArrayList<>();
        for (int index = 0; index < ORGANIZER_COUNT; index++) {
            int organizerId = FIRST_ORGANIZER_ID + index;
            userRows.add(tuple(organizerId, quote(ORGANIZER_NAMES[index]),
                    quote((10 + index) + " Festival Way, Toronto, ON"),
                    quote("organizer" + (index + 1) + "@mytix.example.test"),
                    quote(String.format(Locale.ROOT, "197%d-0%d-15", index, (index % 9) + 1)),
                    quote("organizer")));
        }
        for (int index = 0; index < CUSTOMER_COUNT; index++) {
            int customerId = FIRST_CUSTOMER_ID + index;
            userRows.add(tuple(customerId, quote(customerName(index)),
                    quote((101 + index) + " Sample Street, Toronto, ON"),
                    quote(String.format(Locale.ROOT, "customer%03d@example.test", index + 1)),
                    quote(String.format(Locale.ROOT, "%d-%02d-%02d",
                            1970 + (index % 31), (index % 12) + 1, (index % 27) + 1)),
                    quote("customer")));
        }
        appendValues(sql, "INSERT INTO Users\n"
                + "    (user_id, name, address, email, date_of_birth, user_role)\nVALUES", userRows);

        List<String> organizerRows = new ArrayList<>();
        for (int index = 0; index < ORGANIZER_COUNT; index++) {
            organizerRows.add(tuple(FIRST_ORGANIZER_ID + index, quote("organizer")));
        }
        appendValues(sql, "INSERT INTO Organizer (user_id, user_role) VALUES", organizerRows);

        List<String> customerRows = new ArrayList<>();
        List<String> paymentRows = new ArrayList<>();
        for (int index = 0; index < CUSTOMER_COUNT; index++) {
            int customerId = FIRST_CUSTOMER_ID + index;
            customerRows.add(tuple(customerId, quote("customer")));
            paymentRows.add(tuple(FIRST_PAYMENT_ID + index, customerId,
                    quote(cardNumber(index)), quote(customerName(index)),
                    quote(String.format(Locale.ROOT, "203%d-12-31", 0 + (index % 5))),
                    quote(index % 2 == 0 ? "M5J 2X2" : "M5J 1E6")));
        }
        appendValues(sql, "INSERT INTO Customer (user_id, user_role) VALUES", customerRows);
        appendValues(sql, "INSERT INTO PaymentInfo\n"
                + "    (payment_info_id, customer_id, card_number, card_holder_name, expiry_date, billing_zip)\nVALUES",
                paymentRows);
        line(sql, "");
    }

    private static void appendTaxonomy(StringBuilder sql) {
        appendValues(sql, "INSERT INTO Segment (segment_id, segment_name) VALUES", Arrays.asList(
                tuple(4001, quote("Music")),
                tuple(4002, quote("Arts & Theatre")),
                tuple(4003, quote("Sports"))));
        appendValues(sql, "INSERT INTO Genre (genre_id, genre_name, segment_id) VALUES", Arrays.asList(
                tuple(4101, quote("Rock"), 4001),
                tuple(4102, quote("Pop"), 4001),
                tuple(4103, quote("Musical"), 4002),
                tuple(4104, quote("Comedy"), 4002),
                tuple(4105, quote("Basketball"), 4003),
                tuple(4106, quote("Hockey"), 4003)));
        List<String> artistRows = new ArrayList<>();
        for (int index = 0; index < ARTIST_NAMES.length; index++) {
            artistRows.add(tuple(4201 + index, quote(ARTIST_NAMES[index]), quote(ARTIST_TYPES[index])));
        }
        appendValues(sql, "INSERT INTO ArtistsTeams (artist_id, name, type) VALUES", artistRows);
        line(sql, "");
    }

    private static void appendVenues(StringBuilder sql, Dataset dataset) {
        List<String> venueRows = new ArrayList<>();
        List<String> sectionRows = new ArrayList<>();
        List<String> seatRowRows = new ArrayList<>();
        List<String> seatRows = new ArrayList<>();
        for (VenueSpec venue : dataset.venues) {
            venueRows.add(tuple(venue.id, quote(venue.name), venue.latitude, venue.longitude,
                    quote(venue.address), quote(venue.city), quote(venue.postalCode),
                    quote(venue.country)));
            for (SectionSpec section : venue.sections) {
                sectionRows.add(tuple(venue.id, quote(section.name),
                        quote(section.generalAdmission ? "general" : "reserved"),
                        section.generalAdmission ? Integer.toString(section.capacity) : "NULL"));
                if (!section.generalAdmission) {
                    for (String rowName : section.rowNames) {
                        seatRowRows.add(tuple(venue.id, quote(section.name), quote("reserved"),
                                quote(rowName)));
                        for (int seatNumber = 1; seatNumber <= section.seatsPerRow; seatNumber++) {
                            seatRows.add(tuple(venue.id, quote(section.name), quote(rowName), seatNumber));
                        }
                    }
                }
            }
        }
        appendValues(sql, "INSERT INTO Venue\n"
                + "    (venue_id, name, latitude, longitude, address, city, postal_code, country)\nVALUES",
                venueRows);
        appendValues(sql, "INSERT INTO Section\n"
                + "    (venue_id, section_name, section_type, standing_capacity)\nVALUES", sectionRows);
        appendValues(sql, "INSERT INTO SeatRows\n"
                + "    (venue_id, section_name, section_type, row_name)\nVALUES", seatRowRows);
        appendValues(sql, "INSERT INTO Seats\n"
                + "    (venue_id, section_name, row_name, seat_number)\nVALUES", seatRows);
        line(sql, "");
    }

    private static void appendEvents(StringBuilder sql, Dataset dataset) {
        List<String> eventRows = new ArrayList<>();
        List<String> billingRows = new ArrayList<>();
        for (EventSpec event : dataset.events) {
            eventRows.add(tuple(event.id, quote(event.title), quote(event.description),
                    decimalFromHundredths(event.resaleCapHundredths), event.organizerId, event.genreId));
            for (int index = 0; index < event.artistIds.size(); index++) {
                billingRows.add(tuple(event.id, event.artistIds.get(index), index + 1));
            }
        }
        appendValues(sql, "INSERT INTO Event\n"
                + "    (event_id, title, description, resale_cap_pct, organizer_id, genre_id)\nVALUES",
                eventRows);
        appendValues(sql, "INSERT INTO BillingOrder (event_id, artist_id, billing_rank) VALUES",
                billingRows);
        line(sql, "");
    }

    private static void appendPerformancesAndInventory(StringBuilder sql, Dataset dataset) {
        List<String> performanceRows = new ArrayList<>();
        List<String> tierRows = new ArrayList<>();
        List<String> assignmentRows = new ArrayList<>();
        for (PerformanceSpec performance : dataset.performances) {
            EventSpec event = eventById(dataset, performance.eventId);
            if ("cancelled".equals(performance.status)) {
                performanceRows.add(tuple(performance.id, performance.eventId, performance.venueId,
                        performance.dateExpression(), quote(performance.status),
                        daysAgoExpression(performance.cancellationDaysAgo),
                        quote(performance.cancellationReason), event.organizerId));
            } else {
                performanceRows.add(tuple(performance.id, performance.eventId, performance.venueId,
                        performance.dateExpression(), quote(performance.status), "NULL", "NULL", "NULL"));
            }
            for (Map.Entry<String, Integer> tier : performance.tierPrices.entrySet()) {
                tierRows.add(tuple(performance.id, quote(tier.getKey()),
                        money(tier.getValue())));
            }
            for (Map.Entry<String, String> assignment : performance.sectionTiers.entrySet()) {
                assignmentRows.add(tuple(performance.id, performance.venueId,
                        quote(assignment.getKey()), quote(assignment.getValue())));
            }
        }
        appendValues(sql, "INSERT INTO Performance\n"
                + "    (performance_id, event_id, venue_id, date_time, status, cancellation_date,\n"
                + "     cancellation_reason, cancelled_by_organizer_id)\nVALUES", performanceRows);
        appendValues(sql, "INSERT INTO PriceTier (performance_id, tier_code, price) VALUES",
                tierRows);
        appendValues(sql, "INSERT INTO SectionTierAssignment\n"
                + "    (performance_id, venue_id, section_name, tier_code)\nVALUES", assignmentRows);

        List<String> gaRows = new ArrayList<>();
        for (GaInventory ga : dataset.gaInventory) {
            gaRows.add(tuple(ga.id, ga.performanceId, ga.venueId, quote(ga.sectionName),
                    quote("general"), ga.totalCapacity, ga.totalCapacity - ga.activeSoldCount));
        }
        appendValues(sql, "INSERT INTO GeneralAdmissionCapacity\n"
                + "    (ga_capacity_id, performance_id, venue_id, section_name, section_type,\n"
                + "     total_capacity, remaining_capacity)\nVALUES", gaRows);

        List<String> performanceSeatRows = new ArrayList<>();
        for (SeatInventory seat : dataset.seatInventory) {
            performanceSeatRows.add(tuple(seat.id, seat.performanceId, seat.venueId,
                    quote(seat.sectionName), quote(seat.rowName), seat.seatNumber,
                    seat.blocked ? "TRUE" : "FALSE"));
        }
        appendValues(sql, "INSERT INTO PerformanceSeats\n"
                + "    (performance_seat_id, performance_id, venue_id, section_name, row_name,\n"
                + "     seat_number, blocked_status)\nVALUES", performanceSeatRows);
        line(sql, "");
    }

    private static void appendPurchasesAndTickets(StringBuilder sql, Dataset dataset) {
        List<String> transactionRows = new ArrayList<>();
        for (TransactionSpec transaction : dataset.purchases) {
            transactionRows.add(transactionTuple(transaction));
        }
        appendValues(sql, "INSERT INTO Transactions\n"
                + "    (transaction_id, customer_id, payment_info_id, payment_card_number,\n"
                + "     payment_card_holder_name, payment_expiry_date, payment_billing_zip,\n"
                + "     transaction_type, performance_id, listing_id, transaction_date)\nVALUES",
                transactionRows);

        List<String> ticketRows = new ArrayList<>();
        List<TicketSpec> sortedTickets = new ArrayList<>(dataset.tickets);
        sortedTickets.sort(Comparator.comparingInt(ticket -> ticket.id));
        for (TicketSpec ticket : sortedTickets) {
            ticketRows.add(tuple(ticket.id, ticket.purchaseId, ticket.performanceId,
                    quote(ticket.tierCode), nullable(ticket.performanceSeatId),
                    nullable(ticket.gaCapacityId), money(ticket.faceValueCents),
                    quote(ticket.status)));
        }
        appendValues(sql, "INSERT INTO Tickets\n"
                + "    (ticket_id, purchase_id, performance_id, tier_code, performance_seats_ref,\n"
                + "     general_seats_ref, face_value, status)\nVALUES", ticketRows);

        Map<Integer, TransactionSpec> purchaseById = new HashMap<>();
        for (TransactionSpec purchase : dataset.purchases) {
            purchaseById.put(purchase.id, purchase);
        }
        List<String> ownershipRows = new ArrayList<>();
        for (TicketSpec ticket : sortedTickets) {
            ownershipRows.add(tuple(initialOwnershipId(ticket.id), ticket.id, ticket.customerId,
                    ticket.purchaseId, "NULL", purchaseById.get(ticket.purchaseId).transactionDate,
                    "NULL"));
        }
        appendValues(sql, "INSERT INTO TicketOwnership\n"
                + "    (ownership_id, ticket_id, customer_id, acquired_transaction_id,\n"
                + "     acquired_listing_id, acquired_at, ended_at)\nVALUES", ownershipRows);
        line(sql, "");
    }

    private static void appendCancellations(StringBuilder sql, Dataset dataset) {
        List<String> cancellationRows = new ArrayList<>();
        List<String> refundRows = new ArrayList<>();
        for (CancellationSpec cancellation : dataset.cancellations) {
            cancellationRows.add(tuple(cancellation.id, cancellation.ticketId,
                    cancellation.ownershipId, cancellation.cancelledByUserId,
                    cancellation.cancellationDate, quote(cancellation.reason)));
            refundRows.add(tuple(cancellation.refundId, cancellation.id,
                    money(cancellation.refundCents), cancellation.cancellationDate));
        }
        appendValues(sql, "INSERT INTO TicketCancellation\n"
                + "    (cancellation_id, ticket_id, ownership_id, cancelled_by_user_id,\n"
                + "     cancellation_date, reason)\nVALUES", cancellationRows);
        appendValues(sql, "INSERT INTO Refund\n"
                + "    (refund_id, cancellation_id, amount, refund_date)\nVALUES", refundRows);
        line(sql, "");
    }

    private static void appendResaleMarket(StringBuilder sql, Dataset dataset) {
        for (ListingSpec listing : dataset.listings) {
            line(sql, "INSERT INTO ResaleListing");
            line(sql, "    (listing_id, ticket_id, seller_ownership_id, listing_price,");
            line(sql, "     cap_price_at_listing, status, listed_date)");
            line(sql, "VALUES " + tuple(listing.id, listing.ticketId, listing.sellerOwnershipId,
                    money(listing.listingPriceCents), money(listing.capPriceCents),
                    quote(listing.status), listing.listedDate) + ";");
            if (listing.sale != null) {
                line(sql, "INSERT INTO Transactions");
                line(sql, "    (transaction_id, customer_id, payment_info_id, payment_card_number,");
                line(sql, "     payment_card_holder_name, payment_expiry_date, payment_billing_zip,");
                line(sql, "     transaction_type, performance_id, listing_id, transaction_date)");
                line(sql, "VALUES " + transactionTuple(listing.sale.transaction) + ";");
                line(sql, "UPDATE TicketOwnership SET ended_at = " + listing.sale.saleDate
                        + " WHERE ownership_id = " + listing.sale.sellerOwnershipId + ";");
                line(sql, "INSERT INTO TicketOwnership");
                line(sql, "    (ownership_id, ticket_id, customer_id, acquired_transaction_id,");
                line(sql, "     acquired_listing_id, acquired_at, ended_at)");
                line(sql, "VALUES " + tuple(listing.sale.newOwnershipId, listing.ticketId,
                        listing.sale.buyerId, listing.sale.transaction.id, listing.id,
                        listing.sale.saleDate, "NULL") + ";");
            }
        }
        line(sql, "");
    }

    private static void appendCustomerRestrictions(StringBuilder sql) {
        appendValues(sql, "INSERT INTO CustomerRestriction\n"
                + "    (restriction_id, customer_id, restriction_reason, details, started_at)\nVALUES",
                Arrays.asList(
                    tuple(13001, 2001, quote("possible_scalper"),
                            quote("Purchased 12 tickets and listed 7 within the rolling year"),
                            daysAgoExpression(1)),
                    tuple(13002, 2002, quote("possible_scalper"),
                            quote("Purchased 12 tickets and listed 7 within the rolling year"),
                            daysAgoExpression(1))));
        line(sql, "");
    }

    private static void appendReviews(StringBuilder sql, Dataset dataset) {
        List<String> reviewRows = new ArrayList<>();
        for (ReviewSpec review : dataset.reviews) {
            reviewRows.add(tuple(review.customerId, review.performanceId, quote(review.comment),
                    review.eventRating, review.venueRating, review.reviewDate));
        }
        appendValues(sql, "INSERT INTO Reviews\n"
                + "    (customer_id, performance_id, comment_text, event_rating, venue_rating, review_date)\nVALUES",
                reviewRows);
        line(sql, "");
    }

    private static void appendCountChecks(StringBuilder sql) {
        line(sql, "-- Requirement count checks shown after a successful clean load.");
        line(sql, "SELECT 'organizers' AS requirement_name, COUNT(*) AS actual_count, 5 AS minimum_count FROM Organizer;");
        line(sql, "SELECT 'customers' AS requirement_name, COUNT(*) AS actual_count, 100 AS minimum_count FROM Customer;");
        line(sql, "SELECT 'venues' AS requirement_name, COUNT(*) AS actual_count, 8 AS minimum_count FROM Venue;");
        line(sql, "SELECT 'events' AS requirement_name, COUNT(*) AS actual_count, 20 AS minimum_count FROM Event;");
        line(sql, "SELECT 'performances' AS requirement_name, COUNT(*) AS actual_count, 60 AS minimum_count FROM Performance;");
        line(sql, "SELECT 'purchase_orders' AS requirement_name, COUNT(*) AS actual_count, 300 AS minimum_count FROM Transactions WHERE transaction_type = 'purchase';");
        line(sql, "SELECT 'tickets' AS requirement_name, COUNT(*) AS actual_count, 800 AS minimum_count FROM Tickets;");
        line(sql, "SELECT 'ticket_cancellations' AS requirement_name, COUNT(*) AS actual_count, 1 AS minimum_count FROM TicketCancellation;");
        line(sql, "SELECT 'resale_listings' AS requirement_name, COUNT(*) AS actual_count, 1 AS minimum_count FROM ResaleListing;");
        line(sql, "SELECT 'reviewed_events' AS requirement_name, COUNT(DISTINCT p.event_id) AS actual_count, 10 AS minimum_count FROM Reviews r JOIN Performance p ON p.performance_id = r.performance_id;");
    }

    private static String transactionTuple(TransactionSpec transaction) {
        int customerIndex = transaction.customerId - FIRST_CUSTOMER_ID;
        return tuple(transaction.id, transaction.customerId, transaction.paymentInfoId,
                quote(cardNumber(customerIndex)), quote(customerName(customerIndex)),
                quote(String.format(Locale.ROOT, "203%d-12-31", customerIndex % 5)),
                quote(customerIndex % 2 == 0 ? "M5J 2X2" : "M5J 1E6"),
                quote(transaction.transactionType), nullable(transaction.performanceId),
                nullable(transaction.listingId), transaction.transactionDate);
    }

    private static String customerName(int index) {
        return FIRST_NAMES[index % FIRST_NAMES.length] + " "
                + LAST_NAMES[(index / FIRST_NAMES.length + index) % LAST_NAMES.length];
    }

    private static String cardNumber(int customerIndex) {
        return String.format(Locale.ROOT, "9900%012d", customerIndex + 1);
    }

    private static int paymentId(int customerId) {
        return FIRST_PAYMENT_ID + (customerId - FIRST_CUSTOMER_ID);
    }

    private static int initialOwnershipId(int ticketId) {
        return ticketId + 1000;
    }

    private static String purchaseDateExpression(PerformanceSpec performance, int purchaseId) {
        int sequence = purchaseId - 7001;
        int daysAgo;
        if ("cancelled".equals(performance.status)) {
            daysAgo = performance.cancellationDaysAgo + 25 + (sequence % 25);
        } else if (performance.offsetDays < 0) {
            daysAgo = Math.min(360, (-performance.offsetDays) + 20 + (sequence % 25));
        } else {
            daysAgo = 1 + ((sequence * 11) % 350);
        }
        return daysAgoExpression(daysAgo);
    }

    private static String daysAgoExpression(int daysAgo) {
        return "DATE_SUB(UTC_TIMESTAMP(), INTERVAL " + daysAgo + " DAY)";
    }

    private static VenueSpec venue(int id, String name, String latitude, String longitude,
            String address, String city, String postalCode, String country,
            SectionSpec... sections) {
        return new VenueSpec(id, name, latitude, longitude, address, city, postalCode,
                country, Arrays.asList(sections));
    }

    private static SectionSpec reserved(String name, String[] rowNames, int seatsPerRow) {
        return new SectionSpec(name, false, rowNames, seatsPerRow, rowNames.length * seatsPerRow);
    }

    private static SectionSpec general(String name, int capacity) {
        return new SectionSpec(name, true, new String[0], 0, capacity);
    }

    private static PerformanceSpec performance(int id, int eventId, int venueId,
            int offsetDays, String status) {
        return new PerformanceSpec(id, eventId, venueId, offsetDays, status);
    }

    private static int venueCapacity(VenueSpec venue) {
        return venue.sections.stream().mapToInt(section -> section.capacity).sum();
    }

    private static int sellableCapacity(Dataset dataset, int performanceId) {
        int reserved = (int) dataset.seatsByPerformance.getOrDefault(
                performanceId, Collections.emptyList()).stream().filter(seat -> !seat.blocked).count();
        int general = dataset.gaByPerformance.getOrDefault(performanceId, Collections.emptyList())
                .stream().mapToInt(ga -> ga.totalCapacity).sum();
        return reserved + general;
    }

    private static VenueSpec venueById(Dataset dataset, int venueId) {
        return dataset.venues.stream().filter(venue -> venue.id == venueId).findFirst()
                .orElseThrow(() -> new IllegalStateException("Unknown venue ID " + venueId));
    }

    private static EventSpec eventById(Dataset dataset, int eventId) {
        return dataset.events.stream().filter(event -> event.id == eventId).findFirst()
                .orElseThrow(() -> new IllegalStateException("Unknown event ID " + eventId));
    }

    private static PerformanceSpec performanceById(Dataset dataset, int performanceId) {
        return dataset.performances.stream().filter(performance -> performance.id == performanceId)
                .findFirst().orElseThrow(() ->
                        new IllegalStateException("Unknown performance ID " + performanceId));
    }

    private static TicketSpec ticketById(Dataset dataset, int ticketId) {
        return dataset.tickets.stream().filter(ticket -> ticket.id == ticketId).findFirst()
                .orElseThrow(() -> new IllegalStateException("Unknown ticket ID " + ticketId));
    }

    private static GaInventory gaById(Dataset dataset, int gaId) {
        return dataset.gaInventory.stream().filter(ga -> ga.id == gaId).findFirst()
                .orElseThrow(() -> new IllegalStateException("Unknown GA inventory ID " + gaId));
    }

    private static SeatInventory findSeat(Dataset dataset, int performanceId,
            String sectionName, String rowName, int seatNumber) {
        return dataset.seatsByPerformance.get(performanceId).stream()
                .filter(seat -> seat.sectionName.equals(sectionName)
                        && seat.rowName.equals(rowName) && seat.seatNumber == seatNumber)
                .findFirst().orElseThrow(() -> new IllegalStateException("Unknown deterministic seat."));
    }

    private static String nullable(Integer value) {
        return value == null ? "NULL" : Integer.toString(value);
    }

    private static String quote(String value) {
        return "'" + value.replace("'", "''") + "'";
    }

    private static String money(int cents) {
        return String.format(Locale.ROOT, "%d.%02d", cents / 100, Math.abs(cents % 100));
    }

    private static String decimalFromHundredths(int hundredths) {
        return String.format(Locale.ROOT, "%d.%02d", hundredths / 100,
                Math.abs(hundredths % 100));
    }

    private static String tuple(Object... values) {
        StringBuilder tuple = new StringBuilder("(");
        for (int index = 0; index < values.length; index++) {
            if (index > 0) {
                tuple.append(", ");
            }
            tuple.append(values[index]);
        }
        return tuple.append(')').toString();
    }

    private static void appendValues(StringBuilder sql, String header, List<String> rows) {
        require(!rows.isEmpty(), "Generated INSERT statements may not be empty.");
        line(sql, header);
        for (int index = 0; index < rows.size(); index++) {
            line(sql, "    " + rows.get(index) + (index + 1 == rows.size() ? ";" : ","));
        }
    }

    private static void line(StringBuilder sql, String text) {
        sql.append(text).append(System.lineSeparator());
    }

    private static void require(boolean condition, String message) {
        if (!condition) {
            throw new IllegalStateException(message);
        }
    }

    private static final class Dataset {
        private final List<VenueSpec> venues = new ArrayList<>();
        private final List<EventSpec> events = new ArrayList<>();
        private final List<PerformanceSpec> performances = new ArrayList<>();
        private final List<SeatInventory> seatInventory = new ArrayList<>();
        private final List<GaInventory> gaInventory = new ArrayList<>();
        private final Map<Integer, List<SeatInventory>> seatsByPerformance = new HashMap<>();
        private final Map<Integer, List<GaInventory>> gaByPerformance = new HashMap<>();
        private final List<TransactionSpec> purchases = new ArrayList<>();
        private final List<TicketSpec> tickets = new ArrayList<>();
        private final List<CancellationSpec> cancellations = new ArrayList<>();
        private final List<ListingSpec> listings = new ArrayList<>();
        private final Set<Integer> listedTicketIds = new HashSet<>();
        private final List<ReviewSpec> reviews = new ArrayList<>();
        private int nextTicketId;
        private int nextListingId = 10001;
        private int nextResaleTransactionId = 7501;
        private int nextTransferOwnershipId = 20001;
    }

    private static final class VenueSpec {
        private final int id;
        private final String name;
        private final String latitude;
        private final String longitude;
        private final String address;
        private final String city;
        private final String postalCode;
        private final String country;
        private final List<SectionSpec> sections;

        private VenueSpec(int id, String name, String latitude, String longitude,
                String address, String city, String postalCode, String country,
                List<SectionSpec> sections) {
            this.id = id;
            this.name = name;
            this.latitude = latitude;
            this.longitude = longitude;
            this.address = address;
            this.city = city;
            this.postalCode = postalCode;
            this.country = country;
            this.sections = sections;
        }
    }

    private static final class SectionSpec {
        private final String name;
        private final boolean generalAdmission;
        private final String[] rowNames;
        private final int seatsPerRow;
        private final int capacity;

        private SectionSpec(String name, boolean generalAdmission, String[] rowNames,
                int seatsPerRow, int capacity) {
            this.name = name;
            this.generalAdmission = generalAdmission;
            this.rowNames = rowNames;
            this.seatsPerRow = seatsPerRow;
            this.capacity = capacity;
        }
    }

    private static final class EventSpec {
        private final int id;
        private final String title;
        private final String description;
        private final int resaleCapHundredths;
        private final int organizerId;
        private final int genreId;
        private final List<Integer> artistIds;

        private EventSpec(int id, String title, String description, int resaleCapHundredths,
                int organizerId, int genreId, List<Integer> artistIds) {
            this.id = id;
            this.title = title;
            this.description = description;
            this.resaleCapHundredths = resaleCapHundredths;
            this.organizerId = organizerId;
            this.genreId = genreId;
            this.artistIds = artistIds;
        }
    }

    private static final class PerformanceSpec {
        private final int id;
        private final int eventId;
        private final int venueId;
        private final int offsetDays;
        private final String status;
        private final Map<String, Integer> tierPrices = new LinkedHashMap<>();
        private final Map<String, String> sectionTiers = new LinkedHashMap<>();
        private int cancellationDaysAgo;
        private String cancellationReason;

        private PerformanceSpec(int id, int eventId, int venueId, int offsetDays,
                String status) {
            this.id = id;
            this.eventId = eventId;
            this.venueId = venueId;
            this.offsetDays = offsetDays;
            this.status = status;
        }

        private String dateExpression() {
            if (offsetDays >= 0) {
                return "DATE_ADD(UTC_TIMESTAMP(), INTERVAL " + offsetDays + " DAY)";
            }
            return daysAgoExpression(-offsetDays);
        }
    }

    private static final class SeatInventory {
        private final int id;
        private final int performanceId;
        private final int venueId;
        private final String sectionName;
        private final String rowName;
        private final int seatNumber;
        private final boolean blocked;
        private boolean allocated;

        private SeatInventory(int id, int performanceId, int venueId, String sectionName,
                String rowName, int seatNumber, boolean blocked) {
            this.id = id;
            this.performanceId = performanceId;
            this.venueId = venueId;
            this.sectionName = sectionName;
            this.rowName = rowName;
            this.seatNumber = seatNumber;
            this.blocked = blocked;
        }
    }

    private static final class GaInventory {
        private final int id;
        private final int performanceId;
        private final int venueId;
        private final String sectionName;
        private final int totalCapacity;
        private int allocatedCount;
        private int activeSoldCount;

        private GaInventory(int id, int performanceId, int venueId, String sectionName,
                int totalCapacity) {
            this.id = id;
            this.performanceId = performanceId;
            this.venueId = venueId;
            this.sectionName = sectionName;
            this.totalCapacity = totalCapacity;
        }
    }

    private static final class TransactionSpec {
        private final int id;
        private final int customerId;
        private final int paymentInfoId;
        private final String transactionType;
        private final Integer performanceId;
        private final Integer listingId;
        private final String transactionDate;

        private TransactionSpec(int id, int customerId, int paymentInfoId,
                String transactionType, Integer performanceId, Integer listingId,
                String transactionDate) {
            this.id = id;
            this.customerId = customerId;
            this.paymentInfoId = paymentInfoId;
            this.transactionType = transactionType;
            this.performanceId = performanceId;
            this.listingId = listingId;
            this.transactionDate = transactionDate;
        }

        private static TransactionSpec purchase(int id, int customerId, int paymentInfoId,
                int performanceId, String transactionDate) {
            return new TransactionSpec(id, customerId, paymentInfoId, "purchase",
                    performanceId, null, transactionDate);
        }

        private static TransactionSpec resale(int id, int customerId, int paymentInfoId,
                int listingId, String transactionDate) {
            return new TransactionSpec(id, customerId, paymentInfoId, "resale",
                    null, listingId, transactionDate);
        }
    }

    private static final class TicketSpec {
        private final int id;
        private final int purchaseId;
        private final int performanceId;
        private final int customerId;
        private final String tierCode;
        private final Integer performanceSeatId;
        private final Integer gaCapacityId;
        private final int faceValueCents;
        private String status = "active";

        private TicketSpec(int id, int purchaseId, int performanceId, int customerId,
                String tierCode, Integer performanceSeatId, Integer gaCapacityId,
                int faceValueCents) {
            this.id = id;
            this.purchaseId = purchaseId;
            this.performanceId = performanceId;
            this.customerId = customerId;
            this.tierCode = tierCode;
            this.performanceSeatId = performanceSeatId;
            this.gaCapacityId = gaCapacityId;
            this.faceValueCents = faceValueCents;
        }

        private static TicketSpec reserved(int id, int purchaseId, int performanceId,
                int customerId, String tierCode, int performanceSeatId, int faceValueCents) {
            return new TicketSpec(id, purchaseId, performanceId, customerId, tierCode,
                    performanceSeatId, null, faceValueCents);
        }

        private static TicketSpec general(int id, int purchaseId, int performanceId,
                int customerId, String tierCode, int gaCapacityId, int faceValueCents) {
            return new TicketSpec(id, purchaseId, performanceId, customerId, tierCode,
                    null, gaCapacityId, faceValueCents);
        }
    }

    private static final class CancellationSpec {
        private final int id;
        private final int refundId;
        private final int ticketId;
        private final int ownershipId;
        private final int cancelledByUserId;
        private final String cancellationDate;
        private final String reason;
        private final int refundCents;

        private CancellationSpec(int id, int refundId, int ticketId, int ownershipId,
                int cancelledByUserId, String cancellationDate, String reason,
                int refundCents) {
            this.id = id;
            this.refundId = refundId;
            this.ticketId = ticketId;
            this.ownershipId = ownershipId;
            this.cancelledByUserId = cancelledByUserId;
            this.cancellationDate = cancellationDate;
            this.reason = reason;
            this.refundCents = refundCents;
        }
    }

    private static final class ListingSpec {
        private final int id;
        private final int ticketId;
        private final int sellerOwnershipId;
        private final int listingPriceCents;
        private final int capPriceCents;
        private final String status;
        private final String listedDate;
        private SaleSpec sale;

        private ListingSpec(int id, int ticketId, int sellerOwnershipId,
                int listingPriceCents, int capPriceCents, String status, String listedDate) {
            this.id = id;
            this.ticketId = ticketId;
            this.sellerOwnershipId = sellerOwnershipId;
            this.listingPriceCents = listingPriceCents;
            this.capPriceCents = capPriceCents;
            this.status = status;
            this.listedDate = listedDate;
        }
    }

    private static final class SaleSpec {
        private final TransactionSpec transaction;
        private final int sellerOwnershipId;
        private final int newOwnershipId;
        private final int buyerId;
        private final String saleDate;

        private SaleSpec(TransactionSpec transaction, int sellerOwnershipId,
                int newOwnershipId, int buyerId, String saleDate) {
            this.transaction = transaction;
            this.sellerOwnershipId = sellerOwnershipId;
            this.newOwnershipId = newOwnershipId;
            this.buyerId = buyerId;
            this.saleDate = saleDate;
        }
    }

    private static final class ReviewSpec {
        private final int customerId;
        private final int performanceId;
        private final String comment;
        private final int eventRating;
        private final int venueRating;
        private final String reviewDate;

        private ReviewSpec(int customerId, int performanceId, String comment,
                int eventRating, int venueRating, String reviewDate) {
            this.customerId = customerId;
            this.performanceId = performanceId;
            this.comment = comment;
            this.eventRating = eventRating;
            this.venueRating = venueRating;
            this.reviewDate = reviewDate;
        }
    }
}
